services:
  - type: web
    name: prima-arena-finance
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh && pip install -r requirements.txt
    startCommand: gunicorn 'sistema_financeiro:system.app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 8050
    autoDeploy: true
